config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations", sessions: "sessions"}
  root "static_page#home"
  get "static_page/about"
  resources :exams
  resources :questions
  resources :users, only: [:show]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users, only: [:index, :show]
    resources :exams, only: [:index]
    resources :devise_admin_logs, only: [:index]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: proc{|controller, model| controller.current_user }

  acts_as_paranoid
  after_destroy :update_question_as_deleted

  enum status: [:waitting, :accepted, :deleted]
  enum question_type: [:single_choice, :multiple_choice, :text]

  has_many :options, dependent: :destroy
  belongs_to :subject
  belongs_to :user

  validates :content, presence: true

  accepts_nested_attributes_for :options,
                               reject_if: lambda {|a| a[:content].blank?},
                               allow_destroy: true

  private
  def update_question_as_deleted
    unless user.admin?
      self.update_attributes status: :deleted
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :load_subjects, except: [:index, :destroy]
  
  def index
    @q = Question.with_deleted.ransack params[:q]
    option = params[:option].nil? ? Settings.questions.filter.all : params[:option]
    @questions = @q.result.includes(:subject).send(option).page(params[:page])
      .per Settings.questions.paginate
  end
  
  def show
    @options = @question.options
  end

  def new
    @question.options.build
  end

  def create
    @question.user_id = current_user.id
    @question.status = Question.statuses[:accepted]
    if @question.save
      flash[:success] = t "question.notice.create_success"
      redirect_to admin_question_path @question
    else
      render :new
    end
  end

  def update
    if @question.update_attributes question_params
      redirect_to admin_question_path @question
    else
      render :edit
    end
  end

  def destroy
    @question.really_destroy!
    flash[:success] = t "question.notice.delete_success"
    redirect_to admin_questions_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def question_params
    params.require(:question).permit :content, :subject_id, :question_type,
     :status, options_attributes: [:id, :content, :is_correct]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_subjects, except: [:index, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @questions = current_user.questions.page(params[:page]).per 5
  end

  def show
    @options = @question.options
  end

  def new
    @question = Question.new
    @question.options.build
  end

  def create
    @question = Question.new question_params
    @question.user_id = current_user.id
    if @question.save
      flash[:success] = t "question.notice.create_success"
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update_attributes question_params
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    flash[:success] = t "question.notice.delete_success"
    redirect_to questions_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def question_params
    params.require(:question).permit :content, :subject_id, :question_type,
     options_attributes: [:id, :content, :is_correct]
  end
end

app/views/questions/_edit_form.html.erb
<%= form_for @question do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label :subject_id %>
    <%= select_tag :subject_id,
      options_from_collection_for_select(@subjects, :id, :name,
       @question.subject.id), name: "question[subject_id]", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :question_type %>
    <%= f.select :question_type,
      options_for_select(Question.question_types.keys.to_a, @question.question_type),
      {}, {class: "form-control question-type"} %>
  </div>
  <div id ="option_field">
    <% if @question.text? %>
      <%= f.fields_for :options do |answer| %>
        <div id="text-field">
          <p>
            <%= answer.label :content, "answer" %>
            <div class="col-md-12">
              <%= answer.text_area :content, class: "form-control" %>
            </div>
          </p>
        </div>
      <% end %>
    <% else %>
      <%= f.fields_for :options do |option| %>
        <%= render partial: "option", locals: {f: option} %>
      <% end %>
      <p class="new_option"></p>
      <div class="add_answ">
        <%= add_option t("question.add_option"), f, :options %>
      </div>
    <% end %>
  </div>
  <div class="edit-button">
    <%= f.submit t("question.update"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label :subject_id %>
    <%= select_tag :subject_id,
      options_from_collection_for_select(@subjects, :id, :name,
      params[:subject_id]), name: "question[subject_id]", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :question_type %>
    <%= f.select :question_type,
      options_for_select(Question.question_types.keys.to_a, params[:question_type]),
      {}, {class: "form-control question-type"} %>
  </div>
  <div id ="option_field">
    <%= f.fields_for :options do |builder| %>
      <p>
        <%= render "option_fields", f: builder %>
      </p>
    <% end %>
    <p class="new_option"></p>
  </div>
  <div class="add_answ">
    <%= add_option t("question.add_option"),
      f, :options %>
  </div>
  <div class="sugesst">
    <%= f.submit t("question.sugesst"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/_option.html.erb
<div id="options">
  <%= f.label :content, t("options") %>
  <div class="row">
    <div class="col-md-7">
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="is_correct">
      <div class="col-md-3">
        <%= f.label :is_correct, class: "checkbox inline" do %>
          <%= f.check_box :is_correct, class: "checkbox_left" %>
          <span><%= t "questions.correct_answer" %></span>
        <% end %>
      </div>
      <div class="remove-option">
        <div class="col-md-2">
          <%= remove_option t("question.remove"), f %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/_option_fields.html.erb
<div id="options">
  <%= f.label :content, t("options") %>
  <div class="row">
    <div class="col-md-7">
      <%= f.text_field :content, class: "form_control" %>
    </div>
    <div class="is_correct">
      <div class="col-md-3">
        <%= f.label :is_correct, class: "checkbox inline" do %>
          <%= f.check_box :is_correct, class: "checkbox_left" %>
          <span><%= t "question.correct_answer" %></span>
        <% end %>
      </div>
      <div class="remove-option">
        <div class="col-md-2">
          <%= remove_option t("question.remove"), f %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="answer-field">
  <%= f.label :content, t("question.answer") %>
  <div class="row">
    <div class="col-md-12">
      <%= f.text_area :content, class: "form_control", name: "question[options_attributes][1000][content]" %>
      <%= f.hidden_field :is_correct, value: :true, name: "question[options_attributes][1000][is_correct]" %>
    </div>
  </div>
</div>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.id %></td>
  <td><%= link_to question.content, question_path(question.id) %></td>
  <td><%= question.subject.name %></td>
  <td><%= question.question_type %>
  </td>
  <td><%= question.status.to_s %></td>
  <td><%= %></td>
</tr>

app/views/questions/edit.html.erb
<% provide :title, t("question.edit_question") %>
<h1><%= t "question.edit_question" %></h1>
<div class="col-md-8 col-md-offset-2">
  <%= render "edit_form" %>
</div>

app/views/questions/index.html.erb
<% provide :title, t("question.question_attribute") %>
<div class="row" id="question">
  <div class="col-md-10 col-md-offset-1">
    <h2>
      <b><%= t "question.suggested_question" %></b>
      <%= link_to new_question_path, class: "pull-right" do %>
        <span class="glyphicon glyphicon-plus"></span>
        <%= t "questions.new" %>
      <% end %>
    </h2>
    <table class="table">
      <thead>
        <tr>
          <th class="number_id"><%= t "question.stt" %></th>
          <th class="content"><%= t "question.question" %></th>
          <th class="subject"><%= t "question.subject" %></th>
          <th class="type"><%= t "questions.type" %></th>
          <th class="state"><%= t "question.state" %></th>
          <th class="action"></th>
        </tr>
        <%= render @questions %>
      </thead>
    </table>
    <%= paginate @questions %><br>
    <%= page_entries_info @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<% provide :title, t("question.sugesst_question") %>
<h1><%= t "question.sugesst_question" %></h1>
<div class="col-md-8 col-md-offset-2">
  <%= render "form" %>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1><%= t "question.question" %></h1>
    <table class="table">
      <tr>
        <td><%= t "question.content" %></td>
        <td><%= @question.content %></td>
      </tr>
      <% if can? :read, @question %>
        <tr>
          <td><%= t "question.options" %></td>
          <td>
            <% if @options.any? %>
              <%= render @options %>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td><%= t "question.subject" %></td>
        <td><%= @question.subject.name %> </td>
      </tr>
      <tr>
        <td><%= t "questions.type" %></td>
        <td><%= @question.question_type %></td>
      </tr>
      <tr>
        <td><%= t "question.state" %></td>
        <td>
          <% if @question.waitting? %>
            <p class="btn btn-warning"><%= @question.status %></p>
          <% else %>
            <p class="btn btn-success"> <%= @question.status %> </p>
          <% end %>
        </td>
      </tr>
    </table>
    <% if can? :update, @question %>
      <%= link_to t("action.edit"), edit_question_path(@question), class: "btn btn-primary" %>
      <%= link_to t("action.delete"), question_path(@question),
      method: "delete", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>