config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations", sessions: "sessions"}
  root "static_page#home"
  get "static_page/about"
  resources :exams
  resources :questions
  resources :users, only: [:show]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users, only: [:index, :show]
    resources :exams, only: [:index]
    resources :devise_admin_logs, only: [:index]
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::BaseController
  def index
    @subjects = @subjects.page(params[:page]).per 10
  end

  def new
  end

  def create
    if @subject.save
      NotifyNewSubject.new.notify @subject
      flash[:success] = t "flash.subject_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "flash.subject_failed"
      render :new
    end
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "flash.subject_update_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "flash.subject_update_failed"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "flash.sub_delete_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "flash.sub_delete_failed"
      redirect_to admin_subjects_path
    end
  end

  private
  def subject_params
    params.require(:subject).permit :name
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name, class: "form-control" %>
  <br>
  <%= f.submit t("subjects.new.save"), class: "btn btn-primary" %>
<% end %>

app/views/admin/subjects/edit.html.erb
<% provide :title, t("subjects.edit") %>
<div class="col-lg-3">
  <%= render "layouts/side_bar" %>
</div>
<div class="col-lg-9">
  <h1><%= t "subjects.edit" %></h1>
  <%= render "form" %>
</div>

app/views/admin/subjects/index.html.erb
<% provide :title, t("subjects.index.title") %>
<div class="col-lg-3">
  <%= render "layouts/side_bar" %>
</div>
<div class="col-lg-9">
  <h1><%= t "subjects.index.title" %></h1>
  <h2>
    <%= link_to new_admin_subject_path, class: "pull-right" do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= t "questions.new" %>
    <% end %>
  </h2>
  <table class="table">
    <tr>
      <td><%= t ".name" %></td>
      <td></td>
    </tr>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td>
          <%= link_to t(".edit"), edit_admin_subject_path(subject),
            class: "btn btn-primary" %>
          <%= link_to t(".delete"), admin_subject_path(subject),
            method: :delete, class: "btn btn-danger"  %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= paginate @subjects %><br>
  <%= page_entries_info @subjects %>
</div>

app/views/admin/subjects/new.html.erb
<% provide :title, t("subjects.new.title") %>
<div class="col-lg-3">
  <%= render "layouts/side_bar" %>
</div>
<div class="col-lg-9">
  <h1><%= t "subjects.new.title" %></h1>
  <%= render "form" %>
</div>