config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations", sessions: "sessions"}
  root "static_page#home"
  get "static_page/about"
  resources :exams
  resources :questions
  resources :users, only: [:show]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users, only: [:index, :show]
    resources :exams, only: [:index]
    resources :devise_admin_logs, only: [:index]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :exams, dependent: :destroy
  has_many :questions

  validates :name, presence: true, length: {maximum: 50}

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.uid + "@fts.com"
      user.name     = auth.info.name
      user.password = Devise.friendly_token
      user.password_confirmation = user.password
      user.save
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @q = User.ransack params[:q]
    @users = @q.result.page(params[:page]).per Settings.users.paginate
  end
  
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/views/admin/users/_search_form.html.erb
<%= search_form_for [:admin, @q] do |f| %>
  <%= f.search_field :name_or_email_cont, class: "form-control",
   placeholder: t("admin.users.find_name_or_email") %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= link_to user.name, admin_user_path(user.id) %></td>
  <td><%= user.email %></td>
  <td>
    <% if user.admin? %>
      <div class="role-admin">
        <%= t "admin.users.admin" %>
      </div>
    <% else %>
      <div class="role-user">
        <%= t "admin.users.user" %>
      </div>
    <% end %>
  </td>
  <td><%= user.created_at.strftime("%h %e, %Y") %></td>
  <td>
    <%= link_to t("action.view"), admin_user_path(user.id),
     class: "btn btn-info" %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<div class="col-lg-3">
  <%= render "layouts/side_bar" %>
</div>
  <div class="col-lg-9">
  <div class="row" id="question">
    <div class="col-md-10 col-md-offset-1">
      <h2>
        <b><%= t "admin.users.manage_user" %></b>
      </h2>
      <%= render "search_form" %>
      <br>
      <br>
      <table class="table">
        <thead>
          <tr>
            <th class="number_id"><%= t "admin.users.stt" %></th>
            <th class="name"><%= t "admin.users.name" %></th>
            <th class="email"><%= t "admin.users.email" %></th>
            <th class="Role"><%= t "admin.users.role" %></th>
            <th class="join-date"><%= t "admin.users.join_date" %></th>
            <th class="action"></th>
          </tr>
          <%= render @users %>
        </thead>
      </table>
      <%= paginate @users %><br>
      <%= page_entries_info @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="col-lg-3">
  <%= render "layouts/side_bar" %>
</div>
<div class="col-lg-9">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1><%= @user.name %></h1>
      <table class="table">
        <tr>
          <td><%= t "admin.users.email" %></td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td><%= t "admin.users.role" %></td>
          <td>
            <% if @user.admin? %>
              <div class="btn btn-primary">
                <%= t "admin.users.admin" %>
              </div>
            <% else %>
              <div class="btn btn-success">
                <%= t "admin.users.user" %>
              </div>
            <% end %> 
          </td>
        </tr>
        <tr>
          <td><%= t "admin.users.join_date" %></td>
          <td><%= @user.created_at.strftime("%h %e, %Y") %></td>
        </tr>
      </table>
    </div>
  </div>
</div>