config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations", sessions: "sessions"}
  root "static_page#home"
  get "static_page/about"
  resources :exams
  resources :questions
  resources :users, only: [:show]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    root "questions#index"
    resources :questions
    resources :subjects
    resources :users, only: [:index, :show]
    resources :exams, only: [:index]
    resources :devise_admin_logs, only: [:index]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: proc{|controller, model| controller.current_user }

  acts_as_paranoid
  after_destroy :update_question_as_deleted

  enum status: [:waitting, :accepted, :deleted]
  enum question_type: [:single_choice, :multiple_choice, :text]

  has_many :options, dependent: :destroy
  belongs_to :subject
  belongs_to :user

  validates :content, presence: true

  accepts_nested_attributes_for :options,
                               reject_if: lambda {|a| a[:content].blank?},
                               allow_destroy: true

  private
  def update_question_as_deleted
    unless user.admin?
      self.update_attributes status: :deleted
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :load_subjects, except: [:index, :destroy]
  
  def index
    @q = Question.with_deleted.ransack params[:q]
    option = params[:option].nil? ? Settings.questions.filter.all : params[:option]
    @questions = @q.result.includes(:subject).send(option).page(params[:page])
      .per Settings.questions.paginate
  end
  
  def show
    @options = @question.options
  end

  def new
    @question.options.build
  end

  def create
    @question.user_id = current_user.id
    @question.status = Question.statuses[:accepted]
    if @question.save
      flash[:success] = t "question.notice.create_success"
      redirect_to admin_question_path @question
    else
      render :new
    end
  end

  def update
    if @question.update_attributes question_params
      redirect_to admin_question_path @question
    else
      render :edit
    end
  end

  def destroy
    @question.really_destroy!
    flash[:success] = t "question.notice.delete_success"
    redirect_to admin_questions_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def question_params
    params.require(:question).permit :content, :subject_id, :question_type,
     :status, options_attributes: [:id, :content, :is_correct]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_subjects, except: [:index, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @questions = current_user.questions.page(params[:page]).per 5
  end

  def show
    @options = @question.options
  end

  def new
    @question = Question.new
    @question.options.build
  end

  def create
    @question = Question.new question_params
    @question.user_id = current_user.id
    if @question.save
      flash[:success] = t "question.notice.create_success"
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update_attributes question_params
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    flash[:success] = t "question.notice.delete_success"
    redirect_to questions_path
  end

  private
  def load_subjects
    @subjects = Subject.all
  end

  def question_params
    params.require(:question).permit :content, :subject_id, :question_type,
     options_attributes: [:id, :content, :is_correct]
  end
end

app/views/public_activity/question/_create.html.erb
<li class="list-group-item">
  <span class="glyphicon glyphicon-plus"></span>
  <strong><%= activity.owner.name %></strong>
  <% if a.trackable %>
    <em><%= t "users.question_created" %></em>
    <%= link_to t("Question #{a.trackable.id}"), exam_path(a.trackable) %>
    <%= t "users.in" %> <%= link_to a.trackable.subject.name, exam_path(a.trackable) %>.
    <br>
    <%= a.updated_at %>
  <% else %>
    <%= t "users.question_error" %>
    <% end %>
</li>

app/views/public_activity/question/_destroy.html.erb
<li class="list-group-item">
  <span class="glyphicon glyphicon-minus"></span>
  <strong><%= activity.owner.name %></strong>
  <% if a.trackable %>
    <em><%= t "users.question_created" %></em>
    <%= link_to t("Question #{a.trackable.id}"), exam_path(a.trackable) %>
    <%= t "users.in" %> <%= link_to a.trackable.subject.name, exam_path(a.trackable) %>.
    <br>
    <%= a.updated_at %>
  <% else %>
    <%= t "users.question_error" %>
  <% end %>
</li>

app/views/public_activity/question/_update.html.erb
<li class="list-group-item">
  <span class="glyphicon glyphicon-edit"></span>
  <strong><%= activity.owner.name %></strong>
  <% if a.trackable %>
    <em><%= t "users.question_updated" %></em>
    <%= link_to t("Question #{a.trackable.id}"), exam_path(a.trackable) %>
    <%= t "users.in" %> <%= link_to a.trackable.subject.name, exam_path(a.trackable) %>.
    <br>
    <%= a.updated_at %>
  <% else %>
    <%= t "users.question_error" %>
  <% end %>
</li>